version: 0.0
os: linux
files:
  - source: /
    destination: /home/kim/app/step3/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: kim
    group: kim

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 60
      runas: kim
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: kim
  ValidateService:
    - locaiton: health.sh
      timeout: 60
      runas: kim