version: 0.0
os: linux
files:
  - source: /
    destination: /home/kim/app/step2/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: kim
    group: kim

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: kim